from . import account_account
from . import account_bank_statement
from . import account_invoice
from . import account_journal
from . import account_move
from . import account_payment
from . import account_payment_term
from . import account_reconcile
from . import account_tax
from . import account_tax_template
from . import analytic_account
from . import chart_template
from . import ir_sequence
from . import product
from . import res_config_settings
from . import res_partner
from . import res_partner_bank
