from . import account_invoice
from . import account_payment_term
from . import account_tax
from . import analytic_account
from . import procurement
from . import product_product
from . import product_template
from . import purchase
from . import stock_move
from . import stock_picking
from . import stock_warehouse
from . import res_partner
