# Do NOT update manually; changes here will be overwritten by Copier
_commit: v1.14.2
_src_path: https://github.com/OCA/oca-addons-repo-template.git
ci: GitHub
dependency_installation_mode: PIP
generate_requirements_txt: true
github_check_license: true
github_ci_extra_env: {}
github_enable_codecov: true
github_enable_makepot: false
github_enable_stale_action: false
github_enforce_dev_status_compatibility: true
include_wkhtmltopdf: true
odoo_version: 13.0
org_name: ForgeFlow
org_slug: ForgeFlow
rebel_module_groups: []
repo_description: Multicompany Fixes
repo_name: Multicompany Fixes
repo_slug: multicompany-fixes
repo_website: https://github.com/ForgeFlow/multicompany-fixes
travis_apt_packages: []
travis_apt_sources: []

