from . import account_bank_statement
from . import account_journal
from . import account_move
from . import account_tax
from . import ir_sequence
from . import pos_config
from . import pos_order
from . import pos_payment_method
from . import pos_session
from . import product_pricelist
from . import res_partner
from . import stock_location
from . import stock_picking
