# Part of Odoo. See LICENSE file for full copyright and licensing details.
{
    "name": "Multi Company Fix Account",
    "version": "13.0.1.0.0",
    "summary": "Account fixes",
    "author": "ForgeFlow, Odoo Community Association (OCA)",
    "website": "http://www.forgeflow.com",
    "license": "LGPL-3",
    "depends": ["account", "mcfix_product", "mcfix_analytic"],
    "data": [
        "views/account_journal_dashboard_view.xml",
        "views/account_bank_statement.xml",
        "views/account_move_view.xml",
        "views/reports.xml",
        "views/report_invoice.xml",
        "wizard/account_move_reversal_view.xml",
        "wizard/setup_wizards_view.xml",
        "wizard/wizard_tax_adjustments_views.xml",
        "templates/assets.xml",
    ],
    "sequence": 30,
    "installable": True,
    "application": False,
    "auto_install": True,
}
