from odoo import models, fields, api


class ProductTemplate(models.Model):
    _inherit = 'product.template'

    property_stock_procurement = fields.Many2one(readonly=True)
    property_stock_production = fields.Many2one(readonly=True)
    property_stock_inventory = fields.Many2one(readonly=True)


class ProductProperty(models.Model):
    _inherit = 'product.template.property'

    property_stock_procurement = fields.Many2one(
        'stock.location', "Procurement Location",
        company_dependent=False, domain=[('usage', 'like', 'procurement')],
        help="This stock location will be used, instead of the default one, as the source location for stock moves generated by procurements.")
    property_stock_production = fields.Many2one(
        'stock.location', "Production Location",
        company_dependent=False, domain=[('usage', 'like', 'production')],
        help="This stock location will be used, instead of the default one, as the source location for stock moves generated by manufacturing orders.")
    property_stock_inventory = fields.Many2one(
        'stock.location', "Inventory Location",
        company_dependent=False, domain=[('usage', 'like', 'inventory')],
        help="This stock location will be used, instead of the default one, as the source location for stock moves generated when you do an inventory.")

    @api.model
    def set_properties(self, object, vals, properties=False):
        if vals.get('property_stock_procurement', False):
            self.set_property(object, 'property_stock_procurement', vals.get('property_stock_procurement', False), properties)
        if vals.get('property_stock_production', False):
            self.set_property(object, 'property_stock_production', vals.get('property_stock_production', False), properties)
        if vals.get('property_stock_inventory', False):
            self.set_property(object, 'property_stock_inventory', vals.get('property_stock_inventory', False), properties)
        return super(ProductProperty, self).set_properties(object, vals, properties)