from . import account_invoice
from . import account_payment_term
from . import account_tax
from . import analytic_account
from . import crm_team
from . import product_pricelist
from . import res_config_settings
from . import res_partner
from . import sale
