# Copyright 2017 Creu Blanca
# Copyright 2017 Eficent Business and IT Consulting Services, S.L.
# License LGPL-3.0 or later (https://www.gnu.org/licenses/lgpl.html).

from odoo import models, fields, api


class ProductTemplate(models.Model):
    _inherit = 'product.template'

    property_stock_production = fields.Many2one(readonly=True)
    property_stock_inventory = fields.Many2one(readonly=True)


class ProductProperty(models.TransientModel):
    _inherit = 'product.property'

    property_stock_production = fields.Many2one(
        'stock.location', "Production Location",
        compute='_compute_property_fields',
        readonly=False, domain=[('usage', 'like', 'production')],
        help="This stock location will be used, instead of the "
             "default one, as the source location for stock moves "
             "generated by manufacturing orders.")
    property_stock_inventory = fields.Many2one(
        'stock.location', "Inventory Location",
        compute='_compute_property_fields',
        readonly=False, domain=[('usage', 'like', 'inventory')],
        help="This stock location will be used, instead of the "
             "default one, as the source location for stock moves "
             "generated when you do an inventory.")

    @api.multi
    def get_property_fields(self, object, properties):
        super(ProductProperty, self).get_property_fields(object, properties)
        for rec in self:
            rec.property_stock_production = rec.get_property_value(
                'property_stock_production', object, properties)
            rec.property_stock_inventory = rec.get_property_value(
                'property_stock_inventory', object, properties)

    @api.multi
    def get_property_fields_list(self):
        res = super(ProductProperty, self).get_property_fields_list()
        res.append('property_stock_production')
        res.append('property_stock_inventory')
        return res
