from odoo import models, fields, api


class ProductTemplate(models.Model):
    _inherit = 'product.template'

    property_stock_procurement = fields.Many2one(readonly=True)
    property_stock_production = fields.Many2one(readonly=True)
    property_stock_inventory = fields.Many2one(readonly=True)


class ProductProperty(models.TransientModel):
    _inherit = 'multicompany.property.product'

    property_stock_procurement = fields.Many2one(
        'stock.location', "Procurement Location",
        compute='_compute_property_fields',
        readonly=False, domain=[('usage', 'like', 'procurement')],
        help="This stock location will be used, "
             "instead of the default one, as the source location for"
             " stock moves generated by procurements.")
    property_stock_production = fields.Many2one(
        'stock.location', "Production Location",
        compute='_compute_property_fields',
        readonly=False, domain=[('usage', 'like', 'production')],
        help="This stock location will be used, instead of the "
             "default one, as the source location for stock moves "
             "generated by manufacturing orders.")
    property_stock_inventory = fields.Many2one(
        'stock.location', "Inventory Location",
        compute='_compute_property_fields',
        readonly=False, domain=[('usage', 'like', 'inventory')],
        help="This stock location will be used, instead of the "
             "default one, as the source location for stock moves "
             "generated when you do an inventory.")

    @api.one
    def get_property_fields(self, object, properties):
        super(ProductProperty, self).get_property_fields(object, properties)
        self.property_stock_procurement = self.get_property_value(
            'property_stock_procurement', object, properties)
        self.property_stock_production = self.get_property_value(
            'property_stock_production', object, properties)
        self.property_stock_inventory = self.get_property_value(
            'property_stock_inventory', object, properties)

    @api.model
    def set_properties(self, object, properties=False):
        super(ProductProperty, self).set_properties(object, properties)
        self.set_property(object, 'property_stock_procurement',
                          self.property_stock_procurement.id, properties)
        self.set_property(object, 'property_stock_production',
                          self.property_stock_production.id, properties)
        self.set_property(object, 'property_stock_inventory',
                          self.property_stock_inventory.id, properties)
