# Copyright 2017 Creu Blanca
# Copyright 2017 ForgeFlow, S.L.
# License LGPL-3.0 or later (https://www.gnu.org/licenses/lgpl.html).

from odoo import fields, models


class ProductProperty(models.TransientModel):
    _inherit = "product.property"

    responsible_id = fields.Many2one(
        "res.users",
        string="Responsible",
        compute="_compute_property_fields",
        readonly=False,
        help="This user will be responsible of the next activities "
        "related to logistic operations for this product.",
    )
    property_stock_production = fields.Many2one(
        "stock.location",
        "Production Location",
        compute="_compute_property_fields",
        readonly=False,
        domain="[('usage', '=', 'production'), '|', "
        "('company_id', '=', False), ('company_id', '=', allowed_company_ids[0])]",
        help="This stock location will be used, instead of the "
        "default one, as the source location for stock moves "
        "generated by manufacturing orders.",
    )
    property_stock_inventory = fields.Many2one(
        "stock.location",
        "Inventory Location",
        compute="_compute_property_fields",
        readonly=False,
        domain="[('usage', '=', 'inventory'), '|', "
        "('company_id', '=', False), ('company_id', '=', allowed_company_ids[0])]",
        help="This stock location will be used, instead of the "
        "default one, as the source location for stock moves "
        "generated when you do an inventory.",
    )

    def get_property_fields(self, object, properties):
        super(ProductProperty, self).get_property_fields(object, properties)
        for rec in self:
            rec.responsible_id = rec.get_property_value(
                "responsible_id", object, properties
            )
            rec.property_stock_production = rec.get_property_value(
                "property_stock_production", object, properties
            )
            rec.property_stock_inventory = rec.get_property_value(
                "property_stock_inventory", object, properties
            )

    def get_property_fields_list(self):
        res = super(ProductProperty, self).get_property_fields_list()
        res.append("responsible_id")
        res.append("property_stock_production")
        res.append("property_stock_inventory")
        return res
