from . import test_account_account
from . import test_account_bank_statement
from . import test_account_chart_template_consistency
from . import test_account_invoice
from . import test_account_invoice_consistency
from . import test_account_journal
from . import test_account_journal_consistency
from . import test_account_move
from . import test_account_payment
from . import test_account_reconcile
from . import test_account_tax
from . import test_product
