# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: test Odoo

on:
    push:
        branches: ["12.0"]
    pull_request:
        branches: ["12.0"]

jobs:
    test:
        runs-on: ubuntu-latest
        container: ${{ matrix.container }}
        strategy:
            fail-fast: false
            matrix:
                include:
                    - container: ghcr.io/oca/oca-ci/py3.6-odoo12.0:latest
                    - container: ghcr.io/oca/oca-ci/py3.6-odoo12.0:latest
        env:
            WKHTMLTOPDF_VERSION: "0.12.5"
        services:
            postgres:
                image: postgres:9.6
                env:
                    POSTGRES_USER: odoo
                    POSTGRES_PASSWORD: odoo
                    POSTGRES_DB: odoo
                ports:
                    - 5432:5432
        steps:
            - uses: actions/checkout@v2
              with:
                  persist-credentials: false
            - run: oca_install_addons
            - run: oca_init_test_database
            - name: licenses check
              run: manifestoo -d . check-licenses
            - name: development status check
              run: manifestoo -d . check-dev-status --default-dev-status=Beta
            - run: oca_run_tests
            - uses: codecov/codecov-action@v1
